# baseURL = "https://www.hellobin.top/"
# languageCode = "zh-CN"
# title = "兔儿跑"
# theme = "book"


# [params]
#     staticDir="static"
#     themeColor="theme-base-0d"
#     BookSearch=true
#     BookMenuBundle="/menu"

baseURL: https://www.hellobin.top/
# languageCode: "zh-CN"
title: 兔儿跑
theme: book
disableKinds: ['taxonomy', 'taxonomyTerm']

# Book configuration
disablePathToLower: true
enableGitInfo: true

# Code highlight
# pygmentsStyle: monokailight
pygmentsCodeFences: true

params:
  # (Optional, default 6) Set how many table of contents levels to be showed on page.
  # Use false to hide ToC, note that 0 will default to 6 (https://gohugo.io/functions/default/)
  # You can also specify this parameter per page in front matter
  #  文章得目录层级 在右侧显示， 默认是6个层级都显示
  BookToC: 3

  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be logo.png
  # BookLogo: /logo.png
  # 首页菜单
  BookMenuBundle: /menu/home.md
  # Postgresql 菜单
  MenuPostgreSQLBundle: /menu/postgresql.md
  # MachineLearning 菜单
  MenuMachineLearningBundle: /menu/machine_learning.md
  
  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to '*' to render all sections to menu
#   BookSection: posts

  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo: https://github.com/ivenabc/blog

  # Enable "Edit this page" links for 'doc' page type.
  # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
  # Path must point to 'content' directory of repo.
  # BookEditPath: edit/master/content

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat: '2006-01-02'

  # (Optional, default true) Enables search function with lunr.js,
  # Index is built on fly, therefore it might slowdown your website.
  BookSearch: false

  # (Optional, default none) Search config for flexsearch index.
  # Read documentation at https://github.com/nextapps-de/flexsearch#usage. By default 'balance' preset is used.
  # This option allows to set specific configs for languages support. Must be valid JavaScript object.
  BookSearchConfig: |  
    { cache: true }
